version: '3.8'

networks:
  docktar:
    external: true

services:
  postgres_db:
    image: postgres:latest
    container_name: docktar_db
    restart: always
    environment:
      - POSTGRES_DB=docktar
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5436:5432'
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data

    networks:
      - docktar

volumes:
  postgres_db:
    driver: local